#!/usr/bin/env bash

# login
pio account login -u ${PIO_USERNAME} -p ${PIO_PASSWORD}

# clean target
pio remote -a ${PIO_AGENT} run -e ${PIO_BORAD} -t clean

# run tests
pio remote -a ${PIO_AGENT} test -e ${PIO_BORAD}

# logout when done
pio account logout
